name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * 0"  # Todo domingo às 00:00 UTC
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest  # Ambiente Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Pega o código do seu repositório

      - name: Add upstream remote
        run: git remote add upstream https://github.com/six2dez/reconftw.git  # Adiciona o repositório original

      - name: Fetch upstream changes
        run: git fetch upstream  # Baixa as atualizações do repositório original

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories  # Mescla as alterações

      - name: Push changes to fork
        run: git push origin main  # Envia as alterações para o seu fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação
